apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tms-application
  name: tms-application
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: tms-application
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          value: tmsdb
        - name: RDS_HOSTNAME
          value: mysql
        - name: RDS_PASSWORD
          value: test
        - name: RDS_PORT
          value: "3306"
        - name: RDS_USERNAME
          value: tmsdb-user
        image: norik766/test-management-system:0.0.1-SNAPSHOT
        name: tms-application
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
